### ISSUE TITLE
OWRT 21 legacy is can add back?

### ISSUE THREAD

**Issue by YoshiKill** [fantastic-packages/packages#17]
Hello i see that you dell support for v21 of owrt packges. Can you bring it back for legacy support or its not possible any more? 
p.s thanks Glinet for they "great" support to use old like dinosaurs sh.... firmware...

**Comment by muink** [comment]
21 has been EOL for a year and has been officially removed from the repository.
Due to the capacity of GitHub actions, earlier versions will be completely removed after a period of time after EOL.
You can try using the [23.05](https://fantastic-packages.github.io/packages/releases/23.05/) version of the feeds. (some software that depends on new features of 23.05 may not work)
Or refer to the [Fork guide](https://github.com/fantastic-packages/packages/blob/master/ForkTheProject.md) to build your own feed using the `21.02` branch.
